version: "3.8"

services:
  # Backend API
  webhook-backend:
    image: node:18-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
      - PORT=3002
      - DB_PATH=/app/database/webhook_redistributor.db
      - TZ=America/Sao_Paulo
      - WEBHOOK_TIMEOUT=5000
      - MAX_RETRIES=3
      - LOG_LEVEL=info
    volumes:
      - ./server:/app
      - webhook_data:/app/database
      - /app/node_modules
    ports:
      - "3002:3002"
    networks:
      - webhook_local

  # Frontend React
  webhook-frontend:
    image: node:18-alpine
    working_dir: /app
    command: sh -c "npm install && npm start"
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:3002
      - REACT_APP_FRONTEND_URL=http://localhost:3000
      - TZ=America/Sao_Paulo
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - webhook_local
    depends_on:
      - webhook-backend

volumes:
  webhook_data:
    driver: local

networks:
  webhook_local:
    driver: bridge
