version: "3.8"

services:
  # Backend API
  webhook-backend:
    image: webhook-backend:latest
    environment:
      - NODE_ENV=production
      - PORT=3002
      - DB_PATH=/app/database/webhook_redistributor.db
      - TZ=America/Sao_Paulo
      - WEBHOOK_TIMEOUT=5000
      - MAX_RETRIES=3
      - LOG_LEVEL=info
    volumes:
      - webhook_data:/app/database
    networks:
      - traefik_public
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 5
      labels:
        - traefik.enable=true
        - traefik.http.routers.webhook-backend.rule=Host(`redistribuidor-back.silhouetteexperts.com.br`)
        - traefik.http.routers.webhook-backend.service=webhook-backend
        - traefik.http.routers.webhook-backend.entrypoints=websecure
        - traefik.http.routers.webhook-backend.tls.certresolver=le
        - traefik.http.routers.webhook-backend.tls=true
        - traefik.http.services.webhook-backend.loadbalancer.server.port=3002

  # Frontend React
  webhook-frontend:
    image: webhook-frontend:latest
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=https://redistribuidor-back.silhouetteexperts.com.br
      - REACT_APP_FRONTEND_URL=https://redistribuidor-front.silhouetteexperts.com.br
      - TZ=America/Sao_Paulo
    networks:
      - traefik_public
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 5
      labels:
        - traefik.enable=true
        - traefik.http.routers.webhook-frontend.rule=Host(`redistribuidor-front.silhouetteexperts.com.br`)
        - traefik.http.routers.webhook-frontend.service=webhook-frontend
        - traefik.http.routers.webhook-frontend.entrypoints=websecure
        - traefik.http.routers.webhook-frontend.tls.certresolver=le
        - traefik.http.routers.webhook-frontend.tls=true
        - traefik.http.services.webhook-frontend.loadbalancer.server.port=3000

volumes:
  webhook_data:
    driver: local

networks:
  traefik_public:
    external: true
