version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=webhook_redistributor
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./init-postgres.js:/docker-entrypoint-initdb.d/02-init.js
    ports:
      - "5432:5432"
    networks:
      - webhook_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d webhook_redistributor"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  webhook-backend:
    image: node:18-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DB_TYPE=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=webhook_redistributor
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_PORT=5432
      - TZ=America/Sao_Paulo
      - WEBHOOK_TIMEOUT=5000
      - MAX_RETRIES=3
      - LOG_LEVEL=info
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    networks:
      - webhook_network
    depends_on:
      postgres:
        condition: service_healthy

  # Frontend React
  webhook-frontend:
    image: node:18-alpine
    working_dir: /app
    command: sh -c "npm install && npm start"
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:3001
      - REACT_APP_FRONTEND_URL=http://localhost:3000
      - TZ=America/Sao_Paulo
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - webhook_network
    depends_on:
      - webhook-backend

  # pgAdmin (opcional - para gerenciar o banco)
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@localhost
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - "5050:80"
    networks:
      - webhook_network
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  webhook_network:
    driver: bridge
